# Generated by Django 5.1.3 on 2024-12-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=19.25, max_digits=4),
        ),
    ]
